Chore/dependency-updates
kesko-dev/url-to-pdf-api pull request #4
Opened 2023-01-24 14:06 UTC by aatosm

Will rebase this into develop once the ci-branch has been merged.

Dependency updates and added .slugignore file to reduce slug size in Heroku, which is currently a bit of a problem.

Lets add QA env for these changes and let the customer test it before deploying to production.

2023-01-25 12:18 UTC, nellileinonen-kesko approved these changes

2023-01-31 12:00 UTC, pulpt requested changes
This fails on QA, guessing that bump with puppeteer was too much? Can be checked from logs at `Jan 31 10:32:34Z`

2023-02-01 08:30 UTC, pulpt approved these changes
Aaand the problem got fixed with the buildback change.

2023-02-01 12:46 UTC, aatosm commented
> Aaand the problem got fixed with the buildback change.

Good job! 💯💎 I'll merge this into develop and lets wait feedback from Kesko after that

2023-02-01 12:46 UTC, merged